site_name: Agentic AI Research Development
site_url: "https://kokolopo.site"
nav:
  - Introductions:
     - introductions/index.md
     - introductions/ai-agent.md
     - LLMs:
       - introductions/llms/llm.md
       - introductions/llms/provider.md
  - Tech Stack:
     - tech-stack/overview.md
     - tech-stack/index.md
     - tech-stack/dev-requirement.md
     - tech-stack/cost-simulation.md
     - tech-stack/commercial-b2b.md
  - OWASP:
     - owasp/index.md
     - owasp/prompt-injection.md
     - owasp/sensitive-information-disclosure.md
     - owasp/supply-chain-risks.md
     - owasp/data-model-poisoning.md
     - owasp/improper-output-handling.md
     - owasp/excessive-agency.md
     - owasp/system-prompt-leakage.md
     - owasp/vector-embedding-weaknesses.md
     - owasp/misinformation.md
     - owasp/unbounded-consumption.md
  - LLM Self Hosting:
     - llm-self-hosting/index.md
  
theme:
  name: material
  font:
    text: Open Sans
    code: Red Hat Mono
  logo: assets/rcs-logo.png
  favicon: assets/rcs-logo.png
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: simple/youtube
      # link: https://youtube.com/@james-willett
    # - icon: simple/linkedin
#       link: https://linkedin.com/in/willettjames

copyright: Copyright &copy; 2025 Reka Cipta Solusi